# Generated by Django 4.1.7 on 2023-03-08 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_id', models.IntegerField(db_index=True)),
                ('text', models.TextField()),
                ('title', models.TextField()),
                ('views_count', models.IntegerField(default=0)),
            ],
        ),
    ]
